[build]
  command = "npm run build"
  publish = ".next"
  
[build.environment]
  NODE_VERSION = "18"
  
[functions]
  directory = "netlify/functions"
  
[[redirects]]
  from = "/api/socketio/*"
  to = "/.netlify/functions/socketio"
  status = 200
  
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200